### ISSUE TITLE
In-line help

### ISSUE THREAD

**Issue by genomax** [wdecoster/nanofilt#17]
This is not a issue per se but a request. 

After `pip installing` NanoFilt, in-line help for program is not getting printed cleanly as shown on GitHub page.  `NanoFilt -h or --help`  results in a number of lines of error printout to screen with this being final line `AttributeError: 'CustomHelpFormatter' object has no attribute '_get_default_metavar_for_optional'`. 

This error could be specific to my local environment but wanted to see if you had any suggestions.

**Comment by wdecoster** [comment]
Hi genomax,

I can't immediately reproduce your issue here on my systems (tested on Ubuntu17.10 and CentOS6). 
Could you check the version of your `argparse` module? From the command line: 
    python -c "import argparse ; print(argparse.__version__)"

(Returns 1.1 for me)

If that's older, my first guess would be to try updating argparse (`pip install argparse -U`).

Also, note that my scripts are written for python3. Some might work on Python2/2.7, but this is not guaranteed and untested.

Cheers,
Wouter

**Comment by genomax** [comment]
I get the following with python 3.5.1. This is installed as a module on a cluster. `NanoFilt` is `pip`-installed in `$HOME/.local/bin`.
```
$ python3 -c "import argparse ; print(argparse.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'argparse' has no attribute 'version'
```

**Comment by wdecoster** [comment]
That also suggests it's fairly old, could you try updating?

**Comment by genomax** [comment]
I see `argparse` in my python 3.5.1 module (/path_to/python/3.5.1/lib/python3.5/site-packages/argparse-1.3.0-py3.5.egg). I can get the admins to update if we can identify a specific issue.

**Comment by wdecoster** [comment]
Hm remarkable, I'll try to replicate the issue with argparse-1.3.0.

**Comment by genomax** [comment]
Great. Let me know what you find. We are going to use your script as an example in a python class,

**Comment by wdecoster** [comment]
Could you check if that argparse module (1.3) you described above is also the one being used? On my system the following works: `python -c "import argparse ; print(argparse.__file__)"`, returning the path to the argparse.py file.

As an example in a python class? That's interesting :p

**Comment by genomax** [comment]
I get 
```
$ python3 -c "import argparse ; print(argparse.__file__)"
/path_to/python/3.5.1/lib/python3.5/site-packages/argparse-1.3.0-py3.5.egg/argparse.py
```

**Comment by wdecoster** [comment]
I identified the issue and it should be fixed in NanoFilt v1.9.3:

    pip install nanofilt --upgrade

If that does not pull in v1.9.3 you need to run pip without cache:

    pip install nanofilt --upgrade --no-cache-dir

It appears that the argparse v1.3 was not backward compatible with something I used in v1.1. Slightly annoying.

Please let me know if you encounter further issues or have suggestions/feature requests.

**Comment by genomax** [comment]
@Wouter: I did the upgrade (without and with `--no-cache-dir` ).  But I am still getting the same error when I try `NanoFilt -h `.
```
$ NanoFilt -v
NanoFilt 2.0.0
$ which NanoFilt
~/.local/bin/NanoFilt
$ python3 -c "import argparse ; print(argparse.__file__)"
/path_to/apps/python/3.5.1/lib/python3.5/site-packages/argparse-1.3.0-py3.5.egg/argparse.py
```

Here is something odd. If I make a mistake (unrecognized argument) then I get this
```
$ NanoFilt --ehlp
usage: NanoFilt [-h] [-v] [-l LENGTH] [-q QUALITY] [--minGC MINGC]
                [--maxGC MAXGC] [--headcrop HEADCROP] [--tailcrop TAILCROP]
                [-s SUMMARY] [--readtype {1D,2D,1D2}]
NanoFilt: error: unrecognized arguments: --ehlp
```

**Comment by wdecoster** [comment]
It seems I made a NanoFilt v2.0.0. This is getting increasingly confusing :)

Okay, as soon as I figure out in which caffeine-deprived state I messed up my versioning system it should be fixed.

**Comment by wdecoster** [comment]
I've made a NanoFilt v2.0.1 which should contain the correct changes. Hope this fixes your issue.

I'm intrigued by using my script as an example in a python class - and if there is any feedback I'd love to hear it.

**Comment by genomax** [comment]
Confirming that all is well after upgrade to the latest version. I will email you about the class separately.
